name: Run Puppeteer Bot

on:
  workflow_dispatch: # يتيح لك تشغيل الكود يدوياً من زرة Actions في قيت هب
  schedule:
    - cron: '0 */6 * * *' # (اختياري) يعمل كل 6 ساعات تلقائياً، يمكنك حذفه لو أردت التشغيل اليدوي فقط

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Bot Script
        run: node index.js
